"use client";

import { BrainCircuit, Lightbulb, AlertTriangle, TrendingDown, Target, Zap } from "lucide-react";

export default function InsightsPage() {
  const insights = [
    {
      title: "Elevated Proxy Risk in Lab Complex 2",
      description: "Gait analysis algorithms have detected a 14% increase in unmatched walking patterns entering Lab Complex 2 during afternoon sessions.",
      action: "Recalibrate camera bounding boxes",
      icon: AlertTriangle,
      color: "text-red-400",
      bg: "bg-red-500/10 border-red-500/20"
    },
    {
      title: "Absenteeism Correlation Detected",
      description: "Students missing consecutive Wednesday morning classes have a 68% higher probability of overall academic decline based on historical data.",
      action: "Generate intervention list",
      icon: TrendingDown,
      color: "text-yellow-400",
      bg: "bg-yellow-500/10 border-yellow-500/20"
    },
    {
      title: "Voice Biometrics Accuracy Improved",
      description: "Federated learning on edge devices has successfully increased voice verification confidence from 88% to 94.2% over the last 30 days.",
      action: "View learning metrics",
      icon: Target,
      color: "text-green-400",
      bg: "bg-green-500/10 border-green-500/20"
    },
    {
      title: "Optimized Processing Load",
      description: "AI inference engine successfully re-routed 30% of Face ID processing to idle edge nodes, reducing central server latency by 45ms.",
      action: "View node distribution",
      icon: Zap,
      color: "text-blue-400",
      bg: "bg-blue-500/10 border-blue-500/20"
    }
  ];

  return (
    <div className="p-8 space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-1 text-transparent bg-clip-text bg-gradient-to-r from-white to-zinc-400 flex items-center gap-3">
            <BrainCircuit className="w-8 h-8 text-blue-400" />
            AI Predictive Insights
          </h1>
          <p className="text-zinc-500 text-sm">Actionable intelligence generated by federated learning models.</p>
        </div>
        <button className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2">
          <Lightbulb className="w-4 h-4" />
          Run Deep Analysis
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {insights.map((insight, i) => (
          <div key={i} className={`glass-panel p-6 border ${insight.bg} transition-all duration-300 hover:scale-[1.01]`}>
            <div className="flex gap-4">
              <div className={`p-3 rounded-xl bg-black/20 h-fit`}>
                <insight.icon className={`w-6 h-6 ${insight.color}`} />
              </div>
              <div className="flex-1">
                <h3 className="text-lg font-bold text-white mb-2">{insight.title}</h3>
                <p className="text-zinc-400 text-sm leading-relaxed mb-4">
                  {insight.description}
                </p>
                <button className={`text-sm font-semibold ${insight.color} hover:underline`}>
                  {insight.action} &rarr;
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
